# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 620a721b5c846df30a944cdd89515c24e37b9a61d336700cdbdfe4d2ee5ea6a8e73a15dd3292064c157ce1f8d66773ab4e7a7eb9e2e640ad23c82a273c45fa60

test:
  secret_key_base: 2a8d577e55a568aa772c679a0f5a07a2a9a8849857d89490bec8a14139a85cfad22938456fd5e9dc4ade45114a0632353a4a1580cbdff7f74f5d4b19936bce54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
